ps3/config/routes.rb
Rails.application.routes.draw do

  get 'ps6/index'

  get 'ps5/index'

  get 'ps4/index'

  get 'ps1/page'

  # PS1
  get 'home/index'
  get 'divisions/show'
  post 'divisions/show'
  get 'ps1/page'
  # root 'home#index'

  # PS2
  get 'basics/quotations'
  # root 'basics#quotations'
  post 'basics/quotations'
  get 'basics/export'
  get 'basics/destroy'
  get 'basics/findauthor'
  get 'basics/import'
  post '/basics' => 'basics#import'

  # PS3
  get 'site/index'
  get 'users/index'
  get 'users/admin'
  get 'users/user'
  get 'users/user1'
  root 'site#index'
  get 'users/txt'
  get 'users/dbdump'

  # PS4
  get 'ps4/index'

  # PS5
  get 'ps5/index'

  # PS6
  get 'ps6/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ps3/app/models/quotation.rb
class Quotation < ApplicationRecord
  validates_presence_of :author_name 
  validates_presence_of :category
  validates_presence_of :quote


  def self.search(search)
    # where(' author_name ILIKE ? OR quote ILIKE ? AND id NOT IN (?)', "%#{search}%", "%#{search}%" , list )
    where('author_name ILIKE ? OR quote ILIKE ?', "%#{search}%", "%#{search}%")
  end

end

ps3/app/controllers/basics_controller.rb
class BasicsController < ApplicationController

  require 'rake'
  require 'open-uri'
  require 'nokogiri'

  list = Array.new

  def quotations
    if cookies[:selectq] != nil
      list = cookies[:selectq].split(' ').collect! {|n| n.to_i}
    end
    # XML and Json format
    data = Array.new
    @quotation = Quotation.where.not(id: list)
    respond_to do |format|

      if params[:format] == "json"
        format.json { render json: @quotation }
      elsif params[:format] == "xml"
        @quotation.each do |q|
          data << {:author_name=>q.author_name,:category=>q.category,:quote=>q.quote,:created_at=>q.created_at,:updated_at=>q.updated_at}
        end
        format.xml { render xml: data.to_xml(:root => 'quotations', :children => 'quotation', skip_types: true, :dasherize => false) }
      else
        format.html
      end

    end
    # create new quotation
    if params[:quotation]
      @field = 0
      @quotation = Quotation.new(quotation_params)

      if @quotation.save
        flash[:notice] = 'Quotation was successfully created.'
        @quotation = Quotation.new
      end
    else
      @quotation = Quotation.new
    end

    # cookies list
    if cookies[:selectq] != nil
      list = cookies[:selectq].split(' ').collect! {|n| n.to_i}
      @showlist = list
    end
    # sort by date or category
    if params[:sort_by] == "date"
      @quotations = Quotation.where.not(id: list).order(:created_at)
    else
      @quotations = Quotation.where.not(id: list).order(:category)
    end

    if params[:erase] == "yes"
      cookies.delete(:selectq)
      @quotations = Quotation.order(:created_at)
    end



    # New Category and Old Category input field
    case params[:newcate]
      when "textf"
        @field  = 1
      when "selectf"
        @field  = 2
      else
        @field  = 0
    end
  end
  # get parameter quotation
  def quotation_params
    params.require(:quotation).permit!
  end


  # export xml file
  def export
    @quotation = Quotation.all
    respond_to do |format|
      format.html
      format.json { render json: @quotation }
      format.xml { render xml: @quotation }
    end
  end

  # delete data
  def destroy
    # Quotation.find_by(author_name: params[:author_name]).destroy
    cookies[:selectq] = '' if cookies[:selectq].nil?
    cookies[:selectq] = cookies[:selectq] + ' ' + params[:id]
    redirect_to basics_quotations_path

  end



  # search author_name
  def findauthor
    if cookies[:selectq] != nil
      list = cookies[:selectq].split(' ').collect! {|n| n.to_i}
    end
    if params[:search]
      @results = Quotation.search(params[:search])
      @results = @results.where.not(id: list)
    else
      @results = Quotation.where.not(id: list)
    end
  end

  def import
    doc = Nokogiri::XML(params[:import_xml])
    doc.css('quotation').each do |f|
      Quotation.create do |q|
        q.author_name = f.css("author_name").first.text
        q.category = f.css("category").first.text
        q.quote = f.css("quote").first.text
        q.created_at = f.css("created_at").first.text
        q.updated_at = f.css("updated_at").first.text
      end
    end
  end



end

ps3/app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController


  def show
    @number1 = params[:number1].to_i
    @number2 = params[:number2].to_i


    begin
      @show = @number1 / @number2
    rescue ZeroDivisionError => e
      @msg = e.message
      @name = e.class.name
      @btrace = e.backtrace
      logger.error "About to divide by 0 !!!"
    end

  end

end

ps3/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

ps3/app/controllers/ps1_controller.rb
require 'nokogiri'
require 'open-uri'
require 'htmlentities'

class Ps1Controller < ApplicationController

  def page
    url = "https://www.nytimes.com/"
    @data = Nokogiri::HTML.parse(open(url))
    #puts data.title

    @site_data = @data.css('.story-heading a')

    #@site_data.each do |news|
    # @story_heading = news.text.strip
    # @link_to_story = news['href']

  end
end

ps3/app/controllers/ps4_controller.rb
class Ps4Controller < ApplicationController
  def index
  end
end

ps3/app/controllers/ps5_controller.rb
class Ps5Controller < ApplicationController
  def index
  end
end

ps3/app/controllers/ps6_controller.rb
class Ps6Controller < ApplicationController
  def index
  end
end

ps3/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end


end

ps3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end
  def admin

  end
  def user

  end
  def user1

  end

  def txt
    respond_to do |format|
      format.text { render :plain => File.open(File.join(asset_path "hello.txt"))}
    end

  end


  def dbdump
    # @text = String.new
    #
    #
    # IO.foreach "/home/wanlipa/Desktop/web17-01/ps3/public/hello.txt" do |line|
    # #File.open("/home/wanlipa/Desktop/web17-01/ps3/public/hello.txt").each_line do |line|
    #   #@text += line
    #   #puts @text
    #
    #   @text << line
    #
    # end

  end
end

ps3/app/helpers/ps1_helper.rb
module Ps1Helper
end

ps3/app/helpers/ps4_helper.rb
module Ps4Helper
end

ps3/app/helpers/ps5_helper.rb
module Ps5Helper
end

ps3/app/helpers/ps6_helper.rb
module Ps6Helper
end

ps3/app/views/divisions/show.html.erb
<html>
<head>

  <title>Problem Set-1</title>

  <nav class="navbar navbar-default navbar-inverse">
    <div class="navbar-header">
      <%= link_to "Division",divisions_show_path , class: "navbar-brand"%>
      <%= link_to "Home",root_path,class:"navbar-brand"%>
      <%= link_to "NewYorkTimes",ps1_page_path, class: "navbar-brand", id: "logo"  %>
    </div>
  </nav>

  </head>
<body>

<div>
  <%= form_tag do %>
      <%= number_field_tag "number1" ,nil,min: 0 %>
      / <%= number_field_tag "number2" ,nil,min:0 %>
      <%= submit_tag "submit" , :action => @show %>
  <% end %>
  <br>
  <p>Total : <%= @show %></p>

  <p><%= @msg%> <%= @name%> <%= @btrace%></p>


</div>


</body>

<%= render 'ps1/footer' %>
</html>

ps3/app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<title>Problem Set-1</title>

<nav class="navbar navbar-default navbar-inverse">
  <div class="navbar-header">
    <%= link_to "WEB17-01",root_path, class: "navbar-brand", id: "logo"  %>
  </div>
</nav>

</head>

<body>
<div class="card text-center text-justify text-capitalize ">
  <div class="col-xs-8 col-xs-offset-2">
    <div class = "well well-lg">
      <h4 class="card-title">Solutions to PS1</h4>
      <div class = "card-block">

        <a href="<%= ps1_page_path %>" class="btn btn-danger btn-xlarge">NewYorkTimes Clone</a>
        <a href="<%= divisions_show_path %>" class="btn btn-danger btn-xlarge">Simple Division</a>
        <a href = "https://goo.gl/Z9kAWb" class="btn btn-danger btn-xlarge">Documentation</a>
      </div>
    </div>
  </div>
</div>
</body>


</html>

ps3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ps3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ps3/app/views/ps5/index.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="navbar-header">
    <%= link_to "WEB17-01",root_path, class: "navbar-brand", id: "logo"  %>
  </div>
</nav>

<h2>Problem Set 5 <a href = "https://goo.gl/jdVvHM" class="btn btn-primary btn-small" target="_blank">Documentation</a></h2>
<div class="well">
  <h3>UML Diagram</h3>
  <%= image_tag "UML_Codeisfun.png", style: 'display:block; margin:auto;' %>
</div>

<div class="well">
  <h3>Use Case Diagram</h3>
  <%= image_tag "use_case.png", style: 'display:block; margin:auto;' %>
</div>

<div class="well">
  <h3>Flowchart diagram</h3>
  <%= image_tag "Flowchart.png", style: 'display:block; margin:auto;' %>
</div>

ps3/app/views/users/admin.html.erb
<%= image_tag "harvey.jpg", style: 'display:block; margin:auto; width: 10%'  %>


<ul>
    <li>Name: Harvey Spector</li>
    <li>Age: 22</li>
    <li>Occupation: Student, Asian Institute of Technology </li>
    <li>Marital Status: Single</li>
    <li>Housing Situation: Lives in University Dormitory</li>
    <li>Income: 3000$ per annum</li>
    <li>Short-Term Goal: To Provide a platform for every individual who like to code but having difficulties with it.</li>
    <li>Long-Term Goal: To provide a web application for variety of users from beginner to advanced to improve their problem solving skills. Focusing on all types of users.</li>
    <li>Computer Equipment and Connection: Dell Xps-13 with i7 processor and High speed university Internet connection</li>
</ul>

ps3/app/views/users/dbdump.html.erb
<%= @text %>

ps3/app/views/users/index.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="navbar-header">
    <%= link_to "WEB17-01",root_path, class: "navbar-brand", id: "logo"  %>
  </div>
</nav>

<a href = "https://docs.google.com/a/ait.asia/document/d/1H0S9E6s3e5S0JAlK7jMUUwbj5-vIf0ZxJFEmEKIThRY/edit?usp=sharing" class="btn btn-danger btn-xlarge">Documentation</a>

<h4>Fictious user Profiles</h4>

<ul>
    <!--<a href="users/admin">Harvey Specter(Admin)</a>-->
  <li><%= link_to 'Harvey Specter(Admin)', :controller => :users, :action => :admin %></li>
  <li><%= link_to 'Mike Ross', :controller => :users, :action => :user %></li>
  <li><%= link_to 'Jessica Pearson', :controller => :users, :action => :user1 %></li>
</ul>

<br>
<h4>Jenkins</h4>
<a href="https://goo.gl/TyVZKJ">Capture Jenkins</a>

<br>
<h4 style="color:red">Updated Jenkins</h4>
<p>Change Date: 16/10/2017</p>
<p>Detail: Change jenkins server from port 8080 to link <a href = "http://web1.cs.ait.ac.th/jenkins"> Jenkins Page </a></p>
<p>(So, the old routes http://web1.cs.ait.ac.th:8080 can't connect )</p>

<br>
<h4>Database Dump</h4>
<%= link_to "dbdumpfile", "http://web1.cs.ait.ac.th/ps3/pgdump.txt" %>

ps3/app/views/users/user.html.erb
<%= image_tag "mike.jpg", style: 'display:block; margin:auto; width: 10%'  %>


<ul>
  <li>Name: Mike Ross</li>
  <li>Age: 25</li>
  <li>Occupation: Developer, Google LLC</li>
  <li>Marital Status: Engaged</li>
  <li>Housing Situation: Lives in Bangkok</li>
  <li>Income: 90000$ per annum</li>
  <li>Short-Term Goal: To practice on his coding skills for upcoming interview with facebook.</li>
  <li>Long-Term Goal: Keep on improving my coding skills by constant practice everyday.</li>
  <li>Immediate Questions: What if i am Struck at any topic, can you provide resources to that very topic? </li>
  <li>Computer Equipment and Connection: Macbook pro with i7 processor and High speed Internet connection</li>
</ul>

ps3/app/views/users/user1.html.erb
<%= image_tag "jessica.jpg", style: 'display:block; margin:auto; width: 10%'  %>


<ul>
  <li>Name: Jessica Pearson</li>
  <li>Age: 50</li>
  <li>Occupation: Professor, AIT Thailand</li>
  <li>Marital Status: Divorced</li>
  <li>Housing Situation: Lives in Bangkok</li>
  <li>Income: 65000$ per annum</li>
  <li>Short-Term Goal: Improving my problem solving skills from intense practice.</li>
  <li>Long-Term Goal: I used to focus on total conceptual stuff. I need to get better with my hands on implementations to a particular problem. Implementing my theoretical knowledge into code.</li>
  <li>Immediate Questions: Can i Talk to other developers on this website? </li>
  <li>Computer Equipment and Connection: lenovo thinkpad with i7 processor and High speed Internet connection</li>
</ul>