codeisfun/config/routes.rb
Rails.application.routes.draw do

  resources :problems do
    resources :comments
    resources :solutions
  end


  # get '/comments/new/(:problem_id)', to: 'comments#new', as: :new_comment

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # mount "sites/index" => redirect("https://web1.cs.ait.ac.th/"), :constraints => { :protocol => "http://" }
  # mount "sites/index" => redirect("https://web1.cs.ait.ac.th/"), :constraints => { :subdomain => "" }

  get 'users/index'

  get 'categories/show'
  post 'categories/show'
  get 'categories/index'
  get 'categories/new'
  post 'categories/new'
  get 'categories/edit'
  post 'categories/edit'

  get 'categories/create'
  post 'categories/create'



  # get 'problems/index'
  get 'sites/index'
  root 'sites#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'users/ban'
  get 'users/unban'
  get 'users/show'

  get 'sites/admin'
 # get 'solutions/solve'

  post 'comments/create'
end

codeisfun/app/models/category.rb
class Category < ApplicationRecord
  has_many :problems
  has_paper_trail
  # accepts_nested_attributes_for :problems
end

codeisfun/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:destroy, :edit, :update, :category_owner]
  before_action :category_owner, only: [:create, :new]


  def new
    @category = Category.new
  end

  def show
    @categories = Category.all
  end

  def index
    @categories = Category.all
  end

  def edit

  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_show_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Comment successfully edited"
      redirect_to categories_show_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "Comment successfully destroy"
    redirect_to categories_show_path
  end

  def find_category
    begin
      @category = Category.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      flash[:error] = "Don't have this comment!"
      redirect_to categories_show_path
    end
  end

  def category_owner
    unless current_user.admin?
      flash[:error] = "You don't have authorization!"
      redirect_to categories_show_path
    end
  end

  def category_params
    params.require(:category).permit!
  end

end

codeisfun/app/helpers/categories_helper.rb
module CategoriesHelper
end

codeisfun/app/views/categories/edit.html.erb
<%= form_for :category , :url => {:action => "create", :controller => "categories"} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit "Create" %>
<% end %>

<%= link_to 'Back', categories_show_path %>

codeisfun/app/views/categories/index.html.erb
<h3>List of the Categories</h3>
<ul>
<% @categories.all.each do |cat| %>
    <li><%= cat.name  %>
      <%= link_to 'Edit', categories_edit_path(cat) %>
      <%= link_to 'Destroy', cat , method: :delete, data: { confirm: 'Are you sure?' } %>

    </li>
<% end %>
</ul>

codeisfun/app/views/categories/new.html.erb
<%= form_for :category , :url => {:action => "create", :controller => "categories"} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit "Create" %>
<% end %>

<%= link_to 'Back', categories_show_path %>

codeisfun/app/views/categories/show.html.erb
<div class="center jumbotron">
  <h1>Categories</h1>
  <br>
  <% if current_user.admin? %>
    <%= link_to " Create New Category", categories_new_path , class: "btn btn-success btn-lg btn-xlarge"%>
  <%end%>
  <br>
  <h3>List of the Categories</h3>
    <% @categories.all.each do |cat| %>
    <%= link_to cat.name ,{:controller => :problems , :action => :index , :catid => cat.id } ,class: "btn btn-info btn-lg btn-xlarge"%>
    <% end %>
</div>