codeisfun/config/routes.rb
Rails.application.routes.draw do

  resources :problems do
    resources :comments
    resources :solutions
  end


  # get '/comments/new/(:problem_id)', to: 'comments#new', as: :new_comment

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # mount "sites/index" => redirect("https://web1.cs.ait.ac.th/"), :constraints => { :protocol => "http://" }
  # mount "sites/index" => redirect("https://web1.cs.ait.ac.th/"), :constraints => { :subdomain => "" }

  get 'users/index'

  get 'categories/show'
  post 'categories/show'
  get 'categories/index'
  get 'categories/new'
  post 'categories/new'
  get 'categories/edit'
  post 'categories/edit'

  get 'categories/create'
  post 'categories/create'



  # get 'problems/index'
  get 'sites/index'
  root 'sites#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'users/ban'
  get 'users/unban'
  get 'users/show'

  get 'sites/admin'
 # get 'solutions/solve'

  post 'comments/create'
end

codeisfun/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Codeisfun" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Codeisfun</a>

        <div class="navbar-collapse collapse navbar-responsive-collapse">

          <ul class="nav navbar-nav">
            <li><%= link_to "Contact Admin", "/sites/admin" %></li>
          </ul>
          <ul class="nav navbar-nav">
            <% if user_signed_in? and current_user.admin? %>
                <li><%= link_to "All Users", users_index_path  %></li>
            <%end%>
          </ul>

          <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Problems", categories_show_path  %></li>
            <li> <%= link_to "Your Profile", users_show_path %></li>
          </ul>
              <ul class="nav navbar-nav navbar-right" >
                <%= link_to "Sign out", destroy_user_session_path, method: :delete ,class: "btn btn-danger btn-small"%>
              </ul>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">

          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
        <p>&copy; Web17-01</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>