codeisfun/config/routes.rb
Rails.application.routes.draw do

  resources :problems do
    resources :comments
    resources :solutions
  end


  # get '/comments/new/(:problem_id)', to: 'comments#new', as: :new_comment

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # mount "sites/index" => redirect("https://web1.cs.ait.ac.th/"), :constraints => { :protocol => "http://" }
  # mount "sites/index" => redirect("https://web1.cs.ait.ac.th/"), :constraints => { :subdomain => "" }

  get 'users/index'

  get 'categories/show'
  post 'categories/show'
  get 'categories/index'
  get 'categories/new'
  post 'categories/new'
  get 'categories/edit'
  post 'categories/edit'

  get 'categories/create'
  post 'categories/create'



  # get 'problems/index'
  get 'sites/index'
  root 'sites#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'users/ban'
  get 'users/unban'
  get 'users/show'

  get 'sites/admin'
 # get 'solutions/solve'

  post 'comments/create'
end

codeisfun/app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :user
  belongs_to :problem


=begin
  before_validation :assign_user


  def assign_user
    self.user_id = current_user.id
  end
=end

  def initialize(params = {})
    file = params.delete(:file)
    super
    if file
      self.filename = sanitize_filename(file.original_filename)
      self.content_type = file.content_type
      self.file_contents = file.read
    end
  end

  private
  def sanitize_filename(filename)
    return File.basename(filename)
  end

end

codeisfun/app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :set_user
  before_action :find_problem
  #before_action :find_solution
  before_action :set_solution, only: [:show, :edit, :update, :destroy]

  # GET /solutions
  # GET /solutions.json
  def index
    @solutions = Solution.all
  end

  # GET /solutions/1
  # GET /solutions/1.json
  def show
    @solution = Solution.find(params[:id])
    send_data(@solution.file_contents,
              type: @solution.content_type,
              filename: @solution.filename)
  end

  # GET /solutions/new
  def new
    @solution = Solution.new(id: params[:problem_id])
  end

  # GET /solutions/1/edit
  def edit
  end

  # POST /solutions
  # POST /solutions.json
  def create

    @solution = @problem.solutions.create(solution_params)
    @solution.user_id = current_user.id
    respond_to do |format|
      if @solution.save
        format.html { redirect_to @problem, notice: 'Solution was successfully Submitted.' }
        format.json { render :show, status: :created, location: @solution }
      else
        format.html { render :new }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solutions/1
  # PATCH/PUT /solutions/1.json
  def update
    respond_to do |format|
      if @solution.update(solution_params)
        format.html { redirect_to @solution, notice: 'Solution was successfully updated.' }
        format.json { render :show, status: :ok, location: @solution }
      else
        format.html { render :edit }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solutions/1
  # DELETE /solutions/1.json
  def destroy
    @solution.destroy
    respond_to do |format|
      format.html { redirect_to solutions_url, notice: 'Solution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

=begin
  def solve
    @solution = Solution.find(solution_params)
    @solution.toggle!(:solved)
    flash[:success] = "Solution is approved"
    redirect_to problems_path
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solution
      @solution = Solution.find(params[:id])
    end

  def set_user
    @user = current_user
  end

  def find_problem
    @problem = Problem.find(params[:problem_id])
  end
=begin

  def find_solution
    @solution = @problem.solutions.find(params[:id])
  end

=end

  # Never trust parameters from the scary internet, only allow the white list through.
    def solution_params
      params.require(:solution).permit(:filename, :content_type, :file_contents, :user_id, :problem_id, :file)
    end
end

codeisfun/app/helpers/solutions_helper.rb
module SolutionsHelper
end

codeisfun/app/views/solutions/_form.html.erb
<%= form_for([@problem, @problem.solutions.build]) do |form| %>
    <% if solution.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(solution.errors.count, "error") %> prohibited this solution from being saved:</h2>

          <ul>
            <% solution.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

<!--
    <div class="field">
      <%= form.label :filename %>
      <%= form.text_field :filename, id: :solution_filename %>
    </div>

    <div class="field">
      <%= form.label :content_type %>
      <%= form.text_field :content_type, id: :solution_content_type %>
    </div>

    <div class="field">
      <%= form.label :file_contents %>
      <%= form.text_field :file_contents, id: :solution_file_contents %>
    </div>

    <div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id, id: :solution_user_id %>
    </div>

    <div class="field">
      <%= form.label :problem_id %>
      <%= form.text_field :problem_id, id: :solution_problem_id %>
    </div>
-->


   <!-- <div class="field">
      <%= form.file_field :file %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
-->
    <div class="form-group">
      <%= form.label :solution, class: 'col-sm-2 control-label'  %>
      <div class="col-sm-6">
        <%= form.file_field :file, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= form.submit %>
      </div>

    </div>

<% end %>
<br>

codeisfun/app/views/solutions/edit.html.erb
<h1>Editing Solution</h1>

<%= render 'form', solution: @solution %>

<%= link_to 'Show', @solution %> |
<%= link_to 'Back', solutions_path %>

codeisfun/app/views/solutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Solutions</h1>
<div class="container">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Content type</th>
      <th>Problem Id</th>
      <th>User ID</th>
      <th>Solution</th>
      <th>Approval Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solutions.each do |solution| %>
      <% if current_user.admin? %>
              <tr>
                <td><%= solution.filename %></td>
                <td><%= solution.content_type %></td>
                <td><%= solution.problem_id %></td>
                <td><%= solution.user_id %></td>
                <td><%= link_to "Show", problem_solution_path(@problem,solution) , class: "btn btn-info btn-small"%></td>
                <% if solution.solved? %>
                    <td>Already Approved</td>
                <% else %>
                    <td>Approval Pending...</td>
                <% end %>
              </tr>
      <% end %>
      <% if current_user == solution.user and !current_user.admin? %>
          <tr>
            <td><%= solution.filename %></td>
            <td><%= solution.content_type %></td>
            <td><%= solution.problem_id %></td>
            <td><%= solution.user_id %></td>
            <td><%= link_to "Show", problem_solution_path(@problem,solution) , class: "btn btn-info btn-small"%></td>
            <% if solution.solved? %>
                <td>Already Approved</td>
            <% else %>
                <td>Approval Pending...</td>
            <% end %>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

</div>

codeisfun/app/views/solutions/new.html.erb
<h1>New Solution</h1>

<%= render 'form', solution: @solution %>
<% if !current_user.admin? %>
<%= link_to "My submissions", problem_solutions_path , class: "btn btn-success btn-lg btn-xlarge"%>
<% end %>
<br><br>
<%= link_to 'Back', problem_solutions_path %>

codeisfun/app/views/solutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @solution.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @solution.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  <%= @solution.file_contents %>
</p>

<p>
  <strong>User:</strong>
  <%= @solution.user %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @solution.problem %>
</p>

<%= link_to 'Edit', edit_solution_path(@solution) %> |
<%= link_to 'Back', solutions_path %>